notifications:
  email: false
language: objective-c
osx_image: xcode8
before_install:
  - cd Examples/
  - pod install
script:
  - set -o pipefail
  - xcodebuild $XCODE_ACTION
      -workspace "Examples.xcworkspace"
      -scheme "$TRAVIS_XCODE_SCHEME"
      -sdk "$XCODE_SDK"
      -destination "$XCODE_DESTINATION"
      | xcpretty
matrix:
  include:
    - xcode_scheme: "iOSTests"
      osx_image: xcode7.3
      env:
        - XCODE_ACTION=test
        - XCODE_SDK=iphonesimulator
        - XCODE_DESTINATION="name=iPhone 6s"
